// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8Lz21yfOuzSwmVuYFlfyg_tsVnyJODSc',
    appId: '1:77945450128:web:42d1e7dc0f03bf95db3215',
    messagingSenderId: '77945450128',
    projectId: 'echirp-25cdc',
    authDomain: 'echirp-25cdc.firebaseapp.com',
    storageBucket: 'echirp-25cdc.appspot.com',
    measurementId: 'G-K11V2HMSQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxzrssHTlm5_2e186qDhXWfuAvHAWiH9k',
    appId: '1:77945450128:android:b1363bf345f7d85adb3215',
    messagingSenderId: '77945450128',
    projectId: 'echirp-25cdc',
    storageBucket: 'echirp-25cdc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrytsPTn3Fdyq8RipYfVu4aBSKopdSGI8',
    appId: '1:77945450128:ios:aea39f3f5d35b42edb3215',
    messagingSenderId: '77945450128',
    projectId: 'echirp-25cdc',
    storageBucket: 'echirp-25cdc.appspot.com',
    iosBundleId: 'com.example.echirp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrytsPTn3Fdyq8RipYfVu4aBSKopdSGI8',
    appId: '1:77945450128:ios:aea39f3f5d35b42edb3215',
    messagingSenderId: '77945450128',
    projectId: 'echirp-25cdc',
    storageBucket: 'echirp-25cdc.appspot.com',
    iosBundleId: 'com.example.echirp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8Lz21yfOuzSwmVuYFlfyg_tsVnyJODSc',
    appId: '1:77945450128:web:579a710fa7360958db3215',
    messagingSenderId: '77945450128',
    projectId: 'echirp-25cdc',
    authDomain: 'echirp-25cdc.firebaseapp.com',
    storageBucket: 'echirp-25cdc.appspot.com',
    measurementId: 'G-FGZ1B6JKHR',
  );
}
